language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules

###################
only:
  - master
install:
  npm install
before_install:
# - start your web application and listen on `localhost`
# - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9515 http://localhost &

###################
before_script:
script:
#   - chmod +x deploy-scripts/travis-git-setup.sh
#   - deploy-scripts/travis-git-setup.sh    
#   - hexo clean && hexo deploy
  - hexo g
after_success:
  - chmod +x deploy-scripts/travis-deploy.sh
  - . deploy-scripts/travis-deploy.sh
after_failure:
  - ls -a