language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules

###################
only:
  - master
install:
  npm install
before_install:
# - start your web application and listen on `localhost`
# - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9515 http://localhost &

###################
before_script:
script:
  - hexo deploy -g
after_success:
#   - chmod +x .travis/hexo-deploy.sh
#   - .travis/hexo-deploy.sh
after_failure:
  - ls -a