# ---------------------------------------------------------------
# Theme Information
# ---------------------------------------------------------------
theme: next
language: zh-Hans

# ---------------------------------------------------------------
# Deploy Settings
# ---------------------------------------------------------------
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://keepgoingwm.github.io/ # 网址
root: /
permalink: :year/:month/:day/:title/
# # permalink_defaults:
# permalink: archives/:abbrlink.html
# abbrlink:
#   alg: crc32  # 算法：crc16(default) and crc32
#   rep: hex    # 进制：dec(default) and hex

# hexo-admin authentification
admin:
  username: wangnew2013
  password_hash: $2a$10$9tmQUaYZm.Rfi2u/pdu9NujqMKkrVq9Oe/c5/hWLSBp/Rt1ljDvYe
  secret: $2a$10$qyrlqohBEWj5C8mUicfrl.iSOnMKED5.D2mRUzUyAqRB/nztuBH2S
  # deployCommand: './admin_script/hexo-generate.sh'
  # expire: 60*1

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang  # 国际化文件夹
skip_render:   # 跳过指定文件的渲染

deploy:
  type: git
  repository: git@github.com:keepgoingwm/keepgoingwm.github.io.git
  branch: master

feed:
  type: atom       #feed 类型 (atom/rss2)
  path: atom.xml   #rss 路径
  limit: 0        #rss 中最多生成的文章数，0显示所有

# ---------------------------------------------------------------
# Writing Settings
# ---------------------------------------------------------------
# Writing # 文章布局、写作格式的定义
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0   # 1 为小写， 2 为大写
render_drafts: false  # 显示草稿
post_asset_folder: false  # 启动asset文件夹
relative_link: false # 链接改为与根目录的相对地址
future: true  # 显示未来的文章
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

index_generator:
  per_page: 10 ##首页默认10篇文章标题，如果值为0不分页
archive_generator:
  per_page: 20 ##归档页面默认20篇文章标题
  yearly: true  ##生成年视图
  monthly: true ##生成月视图
tag_generator:
  per_page: 10 ##标签分类页面默认10篇文章
category_generator:
  per_page: 10 ###分类页面默认10篇文章

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
favicon: /favicon.ico
title: wm's Blog # 站点标题
subtitle: 乱弹 # 副标题
description: 这是我的一亩三分地
avatar: /images/avatar/avatar.jpg
author: wm
sidebar:
  position: left

# ---------------------------------------------------------------
# Search Settings
# ---------------------------------------------------------------
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

sitemap: 
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# ---------------------------------------------------------------
# Share/Comment Settings
# ---------------------------------------------------------------
# duoshuo
duoshuo_share: true
duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: wangnew2013
  #admin_nickname: ROOT
duoshuo_shortname: wangnew2013
# 多说热评文章 true 或 false
# duoshuo_hotartical: true

# ---------------------------------------------------------------
# Analytics Settings
# ---------------------------------------------------------------
# Baidu Analytics ID
baidu_analytics: 9e039be8aa081e7d79753005f8a20213

# `阅读全文` 按钮跳转之后是否自动滚动页面到设置，`<!-- more -->` 的地方
scroll_to_more: true

# 是否为侧边栏文章的目录自动添加索引，默认开启。设置为 `false` 关闭
toc_list_number: true

# Use Lato font
use_font_lato: true

